language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
  - secure: QIEhqCRyDhkqbI8fZlFGro78R+H6ZVSQyA09CuSeD7hM4Mj9bnYdI4B4LHUYqA0UvcxspUTzZvYmHr9vGSWGZlzFAc4QKgh5oelo9Xk9zlhV/4PAnso32munruEzH2neOV3GBGxXqdUDSq/QYMB50DRnTSea7Lrsz/seyv5j4CoGAH6wZ9sMFAEDmPRXnEJmfJy55JBZDZgbyQ4N7kMUQL++ObvcQ33RAUqbEdGjRaRFc3R5QUrxkSVhAU7Vp0FWUf1A9QsklVIU6lYi5vuYCRP5xyQYj2vA0dJeGlE5wpCj8ijeU5Bm886IHP6qof3N2pxMNHkwMxf4DQGGqrKpZu9v7YOEYAmj8Rf8+2OlWpkOVOr/lbenx2cZmu20XjunykDH+VPfi0iyus/6Q3n34yxsQ0JPXANausEZQipIT1b+07wpWVogUEYO1tWX247uMZPIFJ1oRRKt23TFeCn0PjPF+YIIrh5/pYrGEgrs4mgOBwaDMzFa0/z+Sc+7TwEn2/f5p15NVkf0VcnlRzn/MlH6VIgYHUtGu9medEX0XN3iJBWEMjxOgboI2dBhOiIk7Zz1pBXvgh5EsX50cZN7cWDTCPgykd/7x9uWlkOMH4d9yzCbtCbOmv7qricWvGYNzvpTzxRkajr5v0T8Wb/trhSXAXV6IOdDhdHsZImXBTk=
  - secure: faTpnKHtZ5/2ghqbiUbyb658lzNHgCA2sk0sFewgk4Vu3ZFbW1s3+qQAezVnfytdzgG+ypLRmLcI1t9Ydoa4AwdSt18zQHgfek8SUSDTh0M0w2J7nMznCbsDblcTAkrqJbPOolMd1+42BMgrewxQyLjoYb9AoAOmrJTkEhbMKSz+ezVLC3G/zsAI/PGJQOOJtqURYfmNQ3UwGE056KCfuUoOfUVDH9tEXhKdENT64S+uT9S4POfaDAdViV+lzjdzUMRNBV7H+7g5HwhrL7py5PSQAEY/9BMoy5gE3LHedAAZu3v7KIgcbAO4b/EfmfoG+1o0Oaxakow35veGcMl2ZRK/Xcvhx9g6JW8g5fU3E3x3QvqATO5f4/s3ekajxmXeh4Oh9J69sHz0wLGqaxlx90KSA+Ntd9yxmzCXNP4C4t8K7cYo95a0UY5tSWQdtJz6og0+r2IuJ9G3Ssk2x5RNTjkY+kwtfnRMFa/6kaLrE0UK1KBBN3AeMK4DpqC02pOG5Sflz8BGcMYBw8PIrpiXlr8qtUcWfyuYN8KEe2zV+wQBpQKNPTmyCgaLrt2PNSLHn/XUC6lZFW28/6U7KRgWRbN4lWPISYYjSJrnKo/Gi3Z9RLAaEExZ4OLMbH2aux9ARvLWxDsJEkTQIh1TwgYhrjyeTMYe9vbJFVVbrTHE+84=
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: nLRb8+VXGuZMTwTbmQC/ivju/rkOmPsjJMK/L5JcdHakmN3istYr5gdCttA3bytayprDqLIERq5Qg0X2jZLg8MyShejTAGnf6rtAxwn3IdKl7RuwN/GjKWLEAfnulLQJYymo6YA504MHaWmlnQKnrqjabAsIqclQTIMaSPptj/jlWlL2Si6qxeJadSX5DqNqwTVKw9tGOier+r+XOD7Kd0IQcEY2bgow/O72WOOEW6R6Fs8t+2Ee/fN7aC3tByjwQpGreEy2/ZgpmHVyWqpebo/ntZlAbLOWvB432EdyLkamqEhPmMU3EZwGtWXcVUVjW5g0yIyjfysIR2c8wEaTIqleYsZMZ2Lli2Wv+b4GnY2PNLF5YwLAqkOfdZMOkhJA/0dXvY0jhA5O37udfx4hV9JdL71zuEO+0FcikxfHQ5BpDFh+c2wpMmaELwLLcl8ZbtafEHLSOpjKnLEYHz9Q+gGXkKNLAFDfaK2FfZHGRWbLg8OezP8CtRNpiQ1t/1pKaOMGckXGEf/0/C51hJskNappJQvPOiJbe06h4fBrVK/3yhVt3SGdMael4jrSgR4TDDgAZ3cZ+pM3nvy+WTGOF8oGuhFsc8/ndrtmmPUlVc+xVU7HZZyhb0QcCk8XswweONLj+VgxlySKpcsQUonDyUoDDoYAsYmPF0uRJw09Qd4=
  on:
    repo: FreeAllMedia/quirk
    branch: master
