language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: fvD3rfVujXDvY/8tHbrf3ISM9FEwMRfRBwCbqauRV9lik+IOYsz2qdCuQ6HlBEeQ8f8S1xp/UQLnHyKh6gZBE2vYEAdd1PAda5NSMZv36wRqCUIRlwrlohH9YIBwNPog3f01Amymd11Pmww8brIebqGqEY0Lbk7SAmur008wYqkJ9lC1VFpoaCIJWBGp/Z5IAjjPBI8nmAK0EIg6968g/DC9OitlT5hXP9XpPx0sJdWpU+NHGFL1UL/pG/KjBlTj7AT3rncWH3c4BVgAvWlkgXVdRzacNzu3XQIWS4ZfT5I26ScEdwiqGI2RwQcTUbPAcwTQQuJu0Y1Ay6W3uSUmX6hAIEoj7PMC3bF5ziTF8fWayB77Se5I8lj8G3zucvRFdmk8Pn1wk9PEUHvGwLEU2u6SyiG2taHHynSW1Hal6vXa20cGO30V2oC7hSh05zgzv89PEQ8/4Cn6REOwBLEF2i+RqCqpQgHzhG2kdLIW3SuSik2ZDHpp9ZtfhRoS9Q1DkGy8WB1q8JV5f8sEkH53FmasXlhc0PHYzLZ67dlS1gg3Phg8GmpJ+jtnXRHe5g6ZcaoHnY1qeYdV56PzMw0gs3eGdJPZXzpstOlWHe7qOgEJ3pTOmScXlPjEYfsKic88GsmATmQC/pY8aZuKZNx974KNarah2XVGmxkeISJfbnI=
env:
  global:
    - secure: 1cw5VDcyZgbnp47e/kRSlzcBTMRuyjWlluD52kGC6oMjBkIOc4FyvY0eOIk3XZNIX8HMCYRUTxX+L282uxEOtuf++EaSWYg/0A0R213tuwOz+66I3IpyaMZzx0G9pxIQEL0y8xfw45TSjxxtcg97NevMZwKcQVm1JYzae+MqaqQEfx6J6WdFdvG+PlvxWKB8EiOGDSkSmPPvvmvSTFZvAe4MKTizV+zzOeYSvkDTIbmp+FJhIQYRG7H+YBloSScvkqf+hRJSCEBkexMmjVvvjBFnhiPLMxiwuq97Dhnc+4MYiFHRX63olOSMtL/pYmlXdNEHPjQmpSC8+4+dSzPDdYkDD82hgVo96eO//pDl4zXGUuOuXU7BePipW1E84Gkob9GYK146uEqbp6CyJPwf4P/N6+Pohu/3gw2TeFj8/ZlMM547jFmyP/HAIPnDn11Mn0xXI+hBnay4Zb/+xPwznBuTsGbeW4gGiZOOEKQvivaxLFHPX40SKyrchnVmgeJzntt0Ekq+/PfN0p2kHLQTJCANjMMdZT2qEwUXZJ7SLiPnuRFMDDMG1BlBPwcaPbztsz3CWmh2okOqxRSLB2mSgj3cGKjee44FBdlV9PokSOZj+zc9/HxZ44HSUo+yYYDryDjZJ2kCpQ4RkmYyTtiNIDXzmPCSN9HpoLK3z9f/JLw=
    - secure: Ug4mARvxIUuVVODVFVkN18O61iy98j1TQdAkxbaouiKrxnS1wvmT83ZvzyROOmUK3Jmu/P3ls99+YghDE6omOMTxrSk0WzYo11TuHsq23HNPtOXNSnqVMzkreM7J57Xyqe/P6evRIFTmky2FrmbIJdLRJccD5+pc2eSd0184USWqI0Io0XIwq5lIFrjJ7bleJLfNJvdbYbqjvHMQZCEfCX8kfICUSsf9ztMdRqVxQd4zyOzzBv2ZReSIUsDx2Mk1YdYKf0gIYwZvpEFfv72/YlZ56rmhjwo5e1KSBtjthRftbB2J82tLNT8otZ5AUZhC6hYowDpUpkktCHB06ne8FNkB1z6lA/3TQHdZg85OLa/6dJKm/9usCYjsJz9SYW6QPwUmKQ06Ocmln9fnLmC3Uq8CtpYDv5aaH+5LZh2vGT02PAeoa2tG/NSzJ8VdyabcJy91C1L706boQCk4Vwb85rsZeu6xy1lvkuUd4XhpmXJ/OdysBChFeCYpLTDl8rV/YxJqYesryyYg2flgh/R15VTU0zwKfY5Df7wcKmlXVroQFcp7On39MTZeRbHoFWpYLO7T6d1DIae5IG7Q6Hw9CwZ11pMJ+6xlall9j1E/LPcN0Umdnu8wxhaPaT7OQ36HkpvEcIHWsEtHxWVzcDjo9JkyAhmHp91FfZ9R1BGNufI=
